/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GRETA_2022;

public class App {
    public String getGreeting() {
        return "Salut tout le monde!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
